# Generated by Django 4.1 on 2023-03-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_tag_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
    ]
