# Generated by Django 4.1 on 2023-03-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_favorite_options_alter_shoppingcard_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveIntegerField(
                verbose_name="Общее доступное количество"
            ),
        ),
    ]
