# Generated by Django 4.1 on 2023-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Является ли пользователь суперюзером.",
                verbose_name="Статус суперпользователя",
            ),
        ),
    ]
