# Generated by Django 4.1 on 2023-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Заблокирован ли пользователь.",
                verbose_name="Статус блокировки пользователя",
            ),
        ),
    ]
