# Generated by Django 4.1 on 2023-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Является ли пользователь суперюзером.",
                verbose_name="Статус служебного персонала",
            ),
        ),
    ]
