name: Yamdb workflow

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-Python@v2
        with:
          python-version: 3.10.4

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          cd api_yamdb
          pip install -r requirements.txt

      - name: Testimg with flake8 and Pytest
        run: |
            python -m flake8


  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Sending message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }}
            ${{ github.actor }} created commit:
                        Commit message: ${{ github.event.commits[0].message }}

                        Repository: ${{ github.repository }}

                        See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
